### ISSUE TITLE
11

### ISSUE THREAD

**Issue by 0MrZhang0** [zhaozijie2022/dynamic-coverage-control#1]
你好 对于你发布的无人机动态区域覆盖有一些问题想请教一下你，可以加个联系方式吗，有偿

**Comment by zjzhaogithub** [comment]
你加一下我QQ吧，1772969776


| |
zjzhao_casia
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/2/2022 14:03 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zjzhaogithub/coverage] 11 (Issue #1) |

你好 对于你发布的无人机动态区域覆盖有一些问题想请教一下你，可以加个联系方式吗，有偿
