### ISSUE TITLE
algo_config

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#10]
您好。我看到uav_dcc_control\algos下有maddpg.py
在uav_dcc_control\config\algo_config里面有MAPPO的配置文件
请问您是否还有MADDPG的配置文件呢？

**Comment by zhaozijie2022** [comment]
MADDPG那个算法来自https://github.com/starry-sky6688/MARL-Algorithms，可以去看下源码是如何使用的

**Comment by DoverDW** [comment]
> MADDPG那个算法来自[https://github.com/starry-sky6688/MARL-Algorithms，可以去看下源码是如何使用的](https://github.com/starry-sky6688/MARL-Algorithms%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8E%BB%E7%9C%8B%E4%B8%8B%E6%BA%90%E7%A0%81%E6%98%AF%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%9A%84)

这个页面找不到了诶

**Comment by Gamelife311** [comment]
> MADDPG那个算法来自[https://github.com/starry-sky6688/MARL-Algorithms，可以去看下源码是如何使用的](https://github.com/starry-sky6688/MARL-Algorithms%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8E%BB%E7%9C%8B%E4%B8%8B%E6%BA%90%E7%A0%81%E6%98%AF%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%9A%84)

好的，谢谢您
