### ISSUE TITLE
AttributeError: 'DCEnv' object has no attribute 'close'报错

### ISSUE THREAD

**Issue by Tongjjiang** [zhaozijie2022/dynamic-coverage-control#13]
你好，我想问一下，在运行代码的时候，dynamic-coverage-control-master\uav_dcc_control\envs\wrappers.py", line 124, in worker
env.close()
AttributeError: 'DCEnv' object has no attribute 'close'
这里一直报错，请问如何解决？

**Comment by zhaozijie2022** [comment]
DCEnv里的step和reset都是直接调用self.env的, 直接补充一个self.env.close()就可以了, 现在已经commit&push了
