### ISSUE TITLE
uav_dcc.py文件里MultiAgentEnv实现的env无法拥有render方法

### ISSUE THREAD

**Issue by boy-prince** [zhaozijie2022/dynamic-coverage-control#14]
我在learner.train()方法里直接使用render会报错TypeError: render() got an unexpected keyword argument 'mode'
我使用openai的mpe文件里MultiAgentEnv实现的env可以成功查找到render方法

**Comment by zhaozijie2022** [comment]
在DCEnv里增加render的调用，与原始mpe方法的render略有不同, 增加了一些代表覆盖范围, 通信范围, 联通保持的图形表示

**Comment by boy-prince** [comment]
作者你好，我在DCEnv添加了render方法并在learner.train里使用，但是使用后出现错误
  File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\wrappers.py", line 116, in worker
    fr = env.render(mode=data)
TypeError: render() got an unexpected keyword argument 'mode'
经查看这里是对render作了一个判断，但是我不太清楚这段代码的含义，请问你有解决方案吗

**Comment by zhaozijie2022** [comment]
这是因为在环境DCEnv里定义了render, 但是在wrapper里没有定义.
wrapper是为了实现多线程的并行环境而做的包装, 在render时一般不考虑多个环境一起render, 可以使用wrapper中利用dummyenv做render
后续我会在wrapper中补充render, 强制mode=rgb, 并返回一个List[np.ndarray], 包含每个环境的渲染画面




| |
zjzhao_casia
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月20日 13:29 |
| 收件人 | ***@***.***> |
| 抄送人 | Zijie ***@***.***>,
State ***@***.***> |
| 主题 | Re: [zhaozijie2022/dynamic-coverage-control] uav_dcc.py文件里MultiAgentEnv实现的env无法拥有render方法 (Issue #14) |

作者你好，我在DCEnv添加了render方法并在learner.train里使用，但是使用后出现错误
File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\wrappers.py", line 116, in worker
fr = env.render(mode=data)
TypeError: render() got an unexpected keyword argument 'mode'
经查看这里是对render作了一个判断，但是我不太清楚这段代码的含义，请问你有解决方案吗

**Comment by boy-prince** [comment]
作者你好，经查看你最新的代码已经成功实现render，但是在何处调用我不太明白，我在learner.train方法里调用只有空窗口，报错如下
  File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\mpe\uav_dcc.py", line 41, in render
    return self.env.render(mode=mode)
  File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\mpe\multiagent\environment.py", line 276, in render
    self.viewers[i].draw_line(self.world.wall[i_w],
AttributeError: 'CoverageWorld' object has no attribute 'wall'

**Comment by zhaozijie2022** [comment]
现在修改好了, 在envs/mpe/environments.py中增加了绘制墙面的代码, 默认boundary=1.2, 在CoverWorld中修改, 目前render可正常运行, 注意pyglet==1.5.27

**Comment by boy-prince** [comment]
作者你好，经过你提醒我成功实现了render，遗憾的是产生了多个render窗口，请问这是什么原因呢？我调用的代码如下，他在learner.train方法部分
    def train(self):
        for iter_ in range(self.n_iters):
            **self.envs.reset()**
            if self.use_linear_lr_decay:
                self.trainer.policy.lr_decay(iter_, self.n_iters)
            _rew = self.rollout(self.rl_buffer, self.envs)
            rollout_info = {"reward": _rew, "rl-collect-rps": _rew / self.max_ep_len}
            **self.envs.render()**
            rl_train_info = self.rl_update()

**Comment by zhaozijie2022** [comment]
这是意料之中的，问题出在wrapper那里，在env_config中设置n_rollout_threads，那个就是并行环境数。
定位到wrapper.py 196行
class SubprocVecEnv:
    ...
    def render(self, mode="rgb_array"):
        for remote in self.remotes:
            remote.send(('render', mode))
        if mode == "rgb_array":
            frame = [remote.recv() for remote in self.remotes]
            return np.stack(frame)
可以设定如果mode="human"只调用self.remotes中的某一个进行render，也就是只调用并行环境中的一个；

一个更好的解决方案是在learner初始化时定义一个test_env, 并行环境数为1, 在test的时候直接调用这个env进行render

**Comment by boy-prince** [comment]
你好，经过观察，我发现env_config中设置n_rollout_threads为32，但是在mappo_yaml文件里设定了
n_eval_rollout_threads: 1  # 用于评估回合的并行环境数
n_render_rollout_threads: 1  # 用于渲染回合的并行环境数
我想它们与渲染有关，但是我不会使用它们

另外，设置n_rollout_thread为1后虽然可以渲染，但是并不是按顺序展示，落点变绿后又会变回未刷新的黑点，并且很卡

**Comment by zhaozijie2022** [comment]
因为我设定了episode最大长度，到达最大长度前就已经done，会直接reset而不是做fill。对于on-policy问题，训练这样可以提高效率，测试的时候你看着什么时候done了结束就行。
你不会使用这两个参数你应该去阅读代码，查看注释或者询问chatGPT，copilot。开源作者不是淘宝客服，这不是代码的问题，为了这个专门提一个issue很没有必要。

**Comment by boy-prince** [comment]
好的，这是我的问题，谢谢你

**Comment by DoverDW** [comment]
> 并不是按顺序展示，落点变绿后又会变回未刷

您好，请问您运行train.py后有渲染的窗口吗，我根据作者最新的代码，运行之后没有渲染窗口

**Comment by DoverDW** [comment]
> 作者你好，经查看你最新的代码已经成功实现render，但是在何处调用我不太明白，我在learner.train方法里调用只有空窗口，报错如下 File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\mpe\uav_dcc.py", line 41, in render return self.env.render(mode=mode) File "E:\SanDiskSecureAccess\dynamic-coverage-control-master\uav_dcc_control\envs\mpe\multiagent\environment.py", line 276, in render self.viewers[i].draw_line(self.world.wall[i_w], AttributeError: 'CoverageWorld' object has no attribute 'wall'

您好，请问您运行train.py后有渲染的窗口吗，我根据作者最新的代码，运行之后没有渲染窗口
