### ISSUE TITLE
最近一次的更新

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#15]
您好，请问您最近一次的更新是对以下脚本做了修改吗
uav_dcc.py
environment.py
CoverageWorld.py
coverage1.py
coverage2.py
此次更新是做了哪些工作呢

**Comment by zhaozijie2022** [comment]
我commit的时候写了是"renfine the render", 另外修改的地方并不多, 你自己对照着commit看一下
我估计总共的修改加一起不到50行，这就不需要单独提一个issue了吧

**Comment by Gamelife311** [comment]
> 我commit的时候写了是"renfine the render", 另外修改的地方并不多, 你自己对照着commit看一下 我估计总共的修改加一起不到50行，这就不需要单独提一个issue了吧

嗯嗯，谢谢您，我对照着修改了，就是怕有什么遗漏
