### ISSUE TITLE
规则约束下的连通保持覆盖)

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#16]
您好，请问在您最新的代码中，场景2(规则约束下的连通保持覆盖)好像还未实现是吗

**Comment by zhaozijie2022** [comment]
已经实现了，有一个为0.0的参数就是连通约束力的比例系数；
这种问题建议先看看代码，不要什么都提issue

**Comment by zhaozijie2022** [comment]
你一个人就提了10个issue，参与了12个issue的讨论。有这时间真不如好好看看代码，这个实现的非常简单，完全工程向，没用到任何复杂的算法。再有问题可以先问问AI，别拿我当客服刷了
