### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by yuequanfighting** [zhaozijie2022/dynamic-coverage-control#18]
大佬好 ，请问您这个代码参考的论文方便提供吗

**Comment by Gamelife311** [comment]
> 大佬好 ，请问您这个代码参考的论文方便提供吗

您好，请问您找到了吗

**Comment by zhaozijie2022** [comment]
回复：这个代码是我的本科毕业设计的对应代码，因为本科毕设是不公开的，所以暂时没有可以提供的论文

**Comment by yuequanfighting** [comment]
> 回复：这个代码是我的本科毕业设计的对应代码，因为本科毕设是不公开的，所以暂时没有可以提供的论文

好的，谢谢
