### ISSUE TITLE
提供包的版本

### ISSUE THREAD

**Issue by ycslnc** [zhaozijie2022/dynamic-coverage-control#2]
你好，请问可以提供一下使用的包的版本吗

**Comment by zhaozijie2022** [comment]
你好，这个项目是我2年前做的了，当时的requirement.txt没有导出，所以具体版本我也忘记了，只记得是基于tf1的，环境部分应该是gym0.10.5，mpe是直接用的代码实现


| |
zjzhao_casia
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Fuxin ***@***.***> |
| 发送日期 | 2023年12月21日 16:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [zhaozijie2022/dynamic-coverage-control] 提供包的版本 (Issue #2) |

你好，请问可以提供一下使用的包的版本吗

**Comment by ycslnc** [comment]
ok，感谢！
