### ISSUE TITLE
求代码

### ISSUE THREAD

**Issue by clll1234567** [zhaozijie2022/dynamic-coverage-control#3]
可以提供能够成功运行的代码吗，有偿

**Comment by zhaozijie2022** [comment]
可以加一下微信? zjzhao3580


| |
zjzhao_casia
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月29日 22:00 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [zhaozijie2022/dynamic-coverage-control] 求代码 (Issue #3) |

可以提供能够成功运行的代码吗，有偿

**Comment by zhaozijie2022** [comment]
基于mappo的代码已上传, 在uav_dcc_control中, 运行`python train.py 0`, 其中0表示使用cuda:0

The code based on MAPPO has been uploaded in uav_dcc_control, run `python train.py 0`, where 0 indicates using cuda:0.
