### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by After55306** [zhaozijie2022/dynamic-coverage-control#4]
请问还能运行导出requirement.txt吗，没有环境备注，复现不了，有偿也行，如果看到的话请联系我，谢谢你

**Comment by zhaozijie2022** [comment]
目前我的环境，python3.9.0，torch=2.2.1，gym=0.21.0，目前requirements.txt已上传

**Comment by After55306** [comment]
谢谢您，辛苦了，目前我可以训练，但是当训练到520多的时候电脑重启了，我想问一下这个需要训练多久啊

**Comment by Gamelife311** [comment]
> 谢谢您，辛苦了，目前我可以训练，但是当训练到520多的时候电脑重启了，我想问一下这个需要训练多久啊

您好，请问您尝试tensorflow那个版本了吗

**Comment by After55306** [comment]
没有，那个tensorflow的版本为1.x的，用不了，不知道怎么解决。

**Comment by Gamelife311** [comment]
> 没有，那个tensorflow的版本为1.x的，用不了，不知道怎么解决。

您好，您知道如何生成readme里面的结果的图吗

**Comment by After55306** [comment]
我目前还没复现成功，最近在忙别的事情，关于结果的生成问题您可以问问贴主

**Comment by Gamelife311** [comment]
> 我目前还没复现成功，最近在忙别的事情，关于结果的生成问题您可以问问贴主

好的，谢谢啦
