### ISSUE TITLE
uav_dcc_control

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#6]
您好，请问uav_dcc_control是独立的项目吗，我看这里用的是pytorch。之前的是基于tensorflow的？

**Comment by zhaozijie2022** [comment]
不算独立吧，是因为之前的tensorflow代码是2年前的，我已经看不懂了，torch版本是重新整理的，目前只实现了场景1和场景2

**Comment by DoverDW** [comment]
> 不算独立吧，是因为之前的tensorflow代码是2年前的，我已经看不懂了，torch版本是重新整理的，目前只实现了场景1和场景2

那麻烦问一下单独用uav_dcc_control也是可以的吧？
