### ISSUE TITLE
训练配置

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#7]
您好，方便问下您的训练配置吗？我运行了uav_dcc_control的train.py后报了内存错误

**Comment by zhaozijie2022** [comment]
目前的设置是torch threads为32，multiprocessing采样并行环境32，可以将torch的threads改为0，并行环境数量改低一些，这样应该可以适配

**Comment by Gamelife311** [comment]
> 目前的设置是torch threads为32，multiprocessing采样并行环境32，可以将torch的threads改为0，并行环境数量改低一些，这样应该可以适配

好的，十分感谢您

**Comment by After55306** [comment]
您好，请问您复现成功了吗

**Comment by Gamelife311** [comment]
> 您好，请问您复现成功了吗

还没有

**Comment by After55306** [comment]
你好，请问我运行一段时间之后电脑蓝屏了，这种情况也是要修改一下训练配置吗（笔记本运行）

**Comment by zhaozijie2022** [comment]
应该是内存溢出了, 修改下并行环境数试一下

**Comment by DoverDW** [comment]
> 你好，请问我运行一段时间之后电脑蓝屏了，这种情况也是要修改一下训练配置吗（笔记本运行）

也有可能是你磁盘的虚存不够，可以自己分配一下
