### ISSUE TITLE
wrappers.py

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#8]
您好。在dynamic-coverage-control-master\uav_dcc_control\envs\wrappers.py中
代码84行的unwrapped函数中
参数VecEnvWrapper报错
请问如何解决呢

**Comment by zhaozijie2022** [comment]
mappo源码中的wrapper这里就是报错，具体原因我也不清楚，但是也不影响运行。
mappo源码参见https://github.com/marlbenchmark/on-policy/blob/main/onpolicy/envs/env_wrappers.py

**Comment by Gamelife311** [comment]
> mappo源码中的wrapper这里就是报错，具体原因我也不清楚，但是也不影响运行。 mappo源码参见https://github.com/marlbenchmark/on-policy/blob/main/onpolicy/envs/env_wrappers.py

好嘞，感谢您。
还有就是这个文件的124行：env.close()
运行train.py最后会出现此错误AttributeError: 'DCEnv' object has no attribute 'close'
不知道您有没有这个问题
我在DCEnv类下面加了一个close函数

**Comment by zhaozijie2022** [comment]
没事, 不用谢. 这个close应该是我的疏忽, 添加一下就可以了

**Comment by After55306** [comment]
我在运行train.py最后也会出现这个错误，请问具体如何解决呢，因为我没学过python，所以我想问一下是在class DummyVecEnv:的类中定义一个close吗，close函数是否为  
  def close(self):
        if self.closed:
            return
        if self.viewer is not None:
            self.viewer.close()
        self.close_extras()
        self.closed = True
但是我看class DummyVecEnv中有close函数为
    def close(self):
        for env in self.envs:
            env.close()
是否需要替换呢，谢谢您

**Comment by DoverDW** [comment]
> DCEnv

在DCEnv类下面加一个close函数

**Comment by Gamelife311** [comment]
> 我在运行train.py最后也会出现这个错误，请问具体如何解决呢，因为我没学过python，所以我想问一下是在class DummyVecEnv:的类中定义一个close吗，close函数是否为 def close(self): if self.closed: return if self.viewer is not None: self.viewer.close() self.close_extras() self.closed = True 但是我看class DummyVecEnv中有close函数为 def close(self): for env in self.envs: env.close() 是否需要替换呢，谢谢您

在DCEnv类下面加一个close函数

**Comment by Tongjjiang** [comment]
> > 我在运行train.py最后也会出现这个错误，请问具体如何解决呢，因为我没学过python，所以我想问一下是在class DummyVecEnv:的类中定义一个close吗，close函数是否为 def close(self): if self.closed: return if self.viewer is not None: self.viewer.close() self.close_extras() self.closed = True 但是我看class DummyVecEnv中有close函数为 def close(self): for env in self.envs: env.close() 是否需要替换呢，谢谢您
> 
> 在DCEnv类下面加一个close函数
你好，请问具体的close函数代码怎么写呢，自己写的好像还是报错！
