### ISSUE TITLE
readme中第三部分results的图

### ISSUE THREAD

**Issue by Gamelife311** [zhaozijie2022/dynamic-coverage-control#9]
您好。使用您的uav_dcc_control训练。请问如何复现您的readme中第三部分results的图呢

**Comment by zhaozijie2022** [comment]
gif图是调用env的render自己画的，训练曲线可以用wandb。
另外torch版本的覆盖率和连通率的计算是存在一个bug。我设定episode的最长时间步为max_ep_len，覆盖率也是计算t=max_ep_len时的覆盖率，但当某一episode成功覆盖结束后，环境会自动重置。比如max_ep_len=80，在第50步时完成覆盖，这一局的覆盖率应该是100%，但环境在t=51时重置，导致t=80的时候只覆盖了70%，此时会计算覆盖率为70%。奖励也同样存在这个问题，后面有时间了我会修复

**Comment by Gamelife311** [comment]
> gif图是调用env的render自己画的，训练曲线可以用wandb。 另外torch版本的覆盖率和连通率的计算是存在一个bug。我设定episode的最长时间步为max_ep_len，覆盖率也是计算t=max_ep_len时的覆盖率，但当某一episode成功覆盖结束后，环境会自动重置。比如max_ep_len=80，在第50步时完成覆盖，这一局的覆盖率应该是100%，但环境在t=51时重置，导致t=80的时候只覆盖了70%，此时会计算覆盖率为70%。奖励也同样存在这个问题，后面有时间了我会修复

感谢您的回答

**Comment by DoverDW** [comment]
> gif图是调用env的render自己画的，训练曲线可以用wandb。 另外torch版本的覆盖率和连通率的计算是存在一个bug。我设定episode的最长时间步为max_ep_len，覆盖率也是计算t=max_ep_len时的覆盖率，但当某一episode成功覆盖结束后，环境会自动重置。比如max_ep_len=80，在第50步时完成覆盖，这一局的覆盖率应该是100%，但环境在t=51时重置，导致t=80的时候只覆盖了70%，此时会计算覆盖率为70%。奖励也同样存在这个问题，后面有时间了我会修复

您好，gif图和训练曲线，是否可以参照 dynamic-coverage-control-master\outdated_tf1_code\experiments 文件下的四个py脚本呢？我不太懂在torch版本的代码中哪里添加绘制图表的代码，是在learner.py中添加吗

**Comment by DoverDW** [comment]
> torch版本的覆盖率和连通率的计算是存在一个bug

您好，请问torch版本的覆盖率和连通率的计算存在的bug，修改的话是在learn.py脚本的某个函数嘛

**Comment by After55306** [comment]
您好，我在运行作者最新的train.py之后，训练数量达到1000后，应该如何操作才能生成readme中的gif图呢？

**Comment by zhaozijie2022** [comment]
see the newest commit
